"""Backend configuration constants for warehouse optimization."""

from __future__ import annotations

ANGLE_STEP_DEGREES = 30.0
FULL_TURN_DEGREES = 360.0
DISCRETE_ANGLES = tuple(
    float(angle) for angle in range(0, int(FULL_TURN_DEGREES), int(ANGLE_STEP_DEGREES))
)

DEFAULT_TIME_BUDGET_SECONDS = 15.0
DEFAULT_BEAM_WIDTH = 6
DEFAULT_CANDIDATE_LIMIT = 12
MAX_ROW_SLOTS = 2048

EXACT_ROOT_CANDIDATE_LIMIT = 18
EXACT_NODE_LIMIT = 3000
EXACT_REFERENCE_POINT_LIMIT = 150
EXACT_TIME_FRACTION = 0.7

MIN_AXIS_BASELINE_SECONDS = 2.0
MAX_AXIS_BASELINE_SECONDS = 8.0
REFINEMENT_TIME_FRACTION = 0.2

MIN_HASH_CELL_SIZE = 100.0
FLOAT_TOLERANCE = 1e-9
